### ISSUE TITLE
ds_create not uploading the full dataset

### ISSUE THREAD

**Issue by haiyingying** [domoinc/domo-python-sdk#60] opened 2021-02-07 23:04 UTC
Hi (again), ds_create is working but it is not uploading the full data frame. There are 974007 in my dataframe and ds_create only uploads 940K rows to DOMO. When I add an extra column, less rows were uploaded. The size of the uploaded data is always around 130Mb. When I tried uploading a smaller dataset of size 400kb all data was uploaded successfully. I am wondering if there is a limit to the dataframe to be uploaded? 

Thanks!

Kind regards
Heidi

**Comment by haiyingying** [comment] 2021-02-07 23:18
I also tried uploading a medium size subset of the dataset I am trying to upload but some of the rows are still missing. Any idea what might cause DOMO to remove some rows?

**Comment by jeremydmorris** [comment] 2021-02-08 18:53
Thanks for the note, I'll take a look at it. I have a hunch as to what is going on.

**Comment by jeremydmorris** [comment] 2021-02-09 17:19
I have a fix available in the ds-update-dropping-data branch. The problem is that the data is broken into chunks and uploading the chunks individually. The current version exits a loop before uploading the last chunk of data. I hope to create a new release with this code by the end of the day today or tomorrow. Until then, you should be able to pip install from that branch. I'll wait to close this issue until the fix has been published.

Just as another comment, I'm considering adding an option to parrallelize the upload, I feel like it is still slower than I'd like it to be and I think that's happening b/c, even though the data is split up, the chunks are still being uploaded in series. I'll probably create another branch for that so we can get this fix out quicker.

**Comment by jeremydmorris** [comment] 2021-02-09 21:28
A fix was released in v0.3.0.3

**Closed by jeremydmorris** 2021-02-09 21:28 UTC

**Comment by haiyingying** [comment] 2021-02-09 23:24
Thank you so much!!
